# TEST PLAYGROUND
GET http://localhost:6901

# Sign up user
POST https://localhost:6901/api/auth/signup
Content-Type: application/json

{
  "email": "user1@test.com",
  "firstName": "user",
  "lastName": "test",
  "password": "123456"
}

# Sign in user
POST http://localhost:6901/api/auth/signin
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "123456"
}

# Get user profile
GET http://localhost:6901/api/auth/profile
Cookie: token={{TEST_TOKEN}}

# Refresh user token
POST http://localhost:6901/api/auth/refresh
Content-Type: application/json
Cookie: refresh={{TEST_REFRESH}}

# Sign out user
POST http://localhost:6901/api/auth/signout
Content-Type: application/json
